FROM 			node:6.2.2

MAINTAINER 		Mika Turunen <mika.turunen@ymail.com>

RUN 			mkdir -p /usr/src/app
WORKDIR 		/usr/src/app

ONBUILD COPY 	../server/package.json /usr/src/app/package.json
ONBUILD RUN 	npm install
ONBUILD COPY 	../server /usr/src/app

EXPOSE 			3000

CMD 			[ "npm", "start" ]
