FROM 			node:6.2.2

MAINTAINER 		Mika Turunen <mika.turunen@ymail.com>

RUN 			mkdir -p /usr/src/app
WORKDIR 		/usr/src/app

COPY 			./server/package.json /usr/src/app/package.json
RUN 			npm install
COPY 			./server /usr/src/app

EXPOSE 			3000
ENV				MONGODB=mongodb://mongo:27017/sword

RUN				ls /usr/src/app
CMD 			[ "npm", "start" ]
